name: CI for Feature Branches

on:
  push:
    branches:
      - frontend-*
      - backend-*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies for frontend
        if: contains(github.ref, 'frontend')
        run: |
          cd client
          npm install

      - name: Install dependencies for backend
        if: contains(github.ref, 'backend')
        run: |
          cd server
          npm install

      # - name: Run tests for frontend
      #   if: contains(github.ref, 'frontend')
      #   run: |
      #     cd client
      #     npm test

      # - name: Run tests for backend
      #   if: contains(github.ref, 'backend')
      #   run: |
      #     cd server
      #     npm test

      - name: Build frontend
        if: contains(github.ref, 'frontend')
        run: |
          cd client
          npm run build

      # - name: Build backend
      #   if: contains(github.ref, 'backend')
      #   run: |
      #     cd server
      #     npm run build

      - name: Set Git user configuration
        run: |
          git config --global user.name "Ketan-Chaudhary"
          git config --global user.email "Ketanchaudhaypoonia@gmail.com"

      - name: Merge into staging branch
        if: success()
        run: |
          git fetch origin staging
          git checkout staging
          git merge ${{ github.ref }} --no-ff -m "Automated merge of ${{ github.ref }} into staging"
          git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git staging
